apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jvb3Q6cm9vdEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvbXlfZGF0YWJhc2VfcGc/c3NsbW9kZT1kaXNhYmxl
  POSTGRES_PASSWORD: cm9vdA==
  SMTP_PASSWORD: MDcwZTg4ZTVlNDkxZmE=
  SMTP_USERNAME: MGQ4MDFlODY2ODgzZjU=
kind: Secret
metadata:
  creationTimestamp: null
  name: citary-secret
  namespace: citary
